#!/bin/bash

echo " "
echo "Building boot.img for 4.2.x"
echo " "

echo "Cleaning possible previous remains"
rm -f build/4.2.x/zImage
rm -f build/4.2.x/ramdisk.gz

echo "Copying zImage and modules"
cp arch/arm/boot/zImage build/4.2.x/zImage

cd build/4.2.x

echo "Packing ramdisk"
../mkbootfs ./boot.img-ramdisk | gzip > ramdisk.gz
echo "Packing boot.img"
../mkbootimg --kernel zImage --ramdisk ramdisk.gz --cmdline "console=null androidboot.hardware=qcom user_debug=31 msm_rtb.filter=0x3F ehci-hcd.park=3" -o boot.img --base "0x80200000" --ramdiskaddr "0x82200000"

echo "Cleaning left overs"
rm -f zImage
rm -f ramdisk.gz

echo "Moving boot.img to build/4.2.x/output/boot.img"
mv -f boot.img output/boot.img

cd ..

echo " "
echo " "
echo " "
echo "boot.img created for JB 4.2.x"


