#!/bin/bash
clear
echo "Flashing build/4.2.x/output/boot.img to phone"
echo
cd build
echo "Pushing boot.img to sdcard..."
echo
./adb push 4.2.x/output/boot.img /sdcard/boot.img
echo "Flashing boot.img to mmcblk0p20..."
./adb shell su -c 'dd if=/sdcard/boot.img of=/dev/block/mmcblk0p20'
echo
echo "Do you want to wipe cache ? ( y / n )"
read wipecache
if [ ${wipecache} == "y" ];
then
 ./adb shell rm /cache/dalvik-cache/*
 ./adb shell rm /data/dalvik-cache/*
fi;
echo "Rebooting Phone..."
./adb reboot
cd ..
